### ISSUE TITLE
新規ルーム作成

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/chat#3]
# 機能
- [x] 友達リストからルームに招待するメンバーを選ぶ
- [x] ルームの作成に成功後ダイアログを閉じる

**Comment by hitochan777** [comment]
@mzki ルーム作成したらそのルームのチャット画面(作成直後なのでチャット履歴はもちろんない)が表示されるでいいでしょうか？

**Comment by mzki** [comment]
問題ありません。

ただ、ルームの作成後に、そのルームへ移動するというアクションを送信してほしいです。

理由は、
ルームへの入場・退出は、それぞれENTER_ROOM, EXIT_ROOMというアクションをサーバに送信することで、
ルームに存在する、アクティブなクライアントを管理したいと考えているからです。

**Comment by hitochan777** [comment]
OKです。wikiにENTER_ROOM, EXIT_ROOMを追加してもらってもいいですか？

**Comment by mzki** [comment]
申し訳ないのですが、ENTER_ROOM, EXIT_ROOMについては一度なかったことにしてください
Clientが現在どのルームを見ているかを、サーバー側では管理しないことにしました

それと、質問があるのですが、以下の認識で問題ないでしょうか

* CREATE_ROOMのようなRoom作成機能についても、Websocketを通してリクエストする
* またRoom作成に失敗したときのエラーメッセージも、Websokcetを通して返信する

**Comment by hitochan777** [comment]
@mzki その認識で問題ないです。
