### ISSUE TITLE
ルーム/友達一覧表示

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/chat#4]
# 機能
- [x] タブでルーム一覧と友達を切り替えることが出来る。
- [x] ログインした段階ではチャットの表示領域には「チャットを始めよう！」みたいな文言を表示する。
- [x] ルーム一覧からルームを1つクリックするとルームのチャットが表示される。プライベートのチャットは今は出来ない。

**Comment by hitochan777** [comment]
@mzki 今回の実装ではルーム/友達一覧はログイン時に全てフェッチするのがいいでしょうか。理想としては最初に全てはフェッチせずに最近チャットをしたルーム/友達を優先的にフェッチして、あとは必要に応じて(スクロールか、検索かわからないが)取ってくるがいいと思いますが。。。

**Comment by mzki** [comment]
今回は、一度にすべて取得する方式にさせてください。

メッセージの取得では、少しづつフェッチする方式にしていますが、これがうまく動作できたなら、
ルーム/友達一覧の取得も理想形にシフトしていこうと考えています。
